//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargoDetails
    {
        public int CargoDetailID { get; set; }
        public int ShipID { get; set; }
        public int MovementID { get; set; }
        public string CargoDescription { get; set; }
        public string CargoType { get; set; }
        public decimal Weight { get; set; }
        public int Units { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> EstimatedDeliveryDate { get; set; }
        public string CustomsDetails { get; set; }
    
        public virtual ShipMovements ShipMovements { get; set; }
        public virtual Ships Ships { get; set; }
    }
}
