//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportData
    {
        public int DataID { get; set; }
        public int ReportID { get; set; }
        public string DataKey { get; set; }
        public string DataValue { get; set; }
    
        public virtual Reports Reports { get; set; }
    }
}
