//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ships
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ships()
        {
            this.CargoDetails = new HashSet<CargoDetails>();
            this.ShipMovements = new HashSet<ShipMovements>();
        }
    
        public int ShipID { get; set; }
        public string ShipName { get; set; }
        public string ShipType { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> PortID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CargoDetails> CargoDetails { get; set; }
        public virtual Ports Ports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipMovements> ShipMovements { get; set; }
    }
}
